//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interview_Tracker.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public int InterviewId { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string InterviewType { get; set; }
        public string InterviewerName { get; set; }
        public string InterviewStatus { get; set; }
        public string FollowUpActions { get; set; }
        public Nullable<bool> ThankYouNoteSent { get; set; }
        public string Notes { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Job Job { get; set; }
    }
}
